version: '3.7'

services:
  web:
    restart: always
    image: nginx:latest
    labels:
      - "traefik.http.routers.nginx-php.rule=Host(`nginx-php.tote.rocks`)"
      - "traefik.http.routers.nginx-php.tls.certresolver=cloudflare"
      - "traefik.http.routers.nginx-php.tls=true"
      - "traefik.enable=true"
    expose:
      - 80
    volumes:
      - ./src:/src/:rw,cached
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - ./.env
    links:
      - php
      - db
    networks:
      - traefik
      - internal
  php:
    restart: always
    build: .
    expose:
      - 9000
    volumes:
      - ./src:/src/:rw,cached
      - ./etc/php.ini:/usr/local/etc/php/conf.d/00_base-example.ini:ro
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - internal
  db:
    image: mysql:5.6.41
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - ./.env
    networks:
      - internal
volumes:
  db-data:
networks:
  traefik:
    name: traefik
    external: true
  internal:
    name: internal
